on:
  push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Run
      run: |
        ls -l
        git clone --depth=1 https://github.com/ftc-team-8813/ftc_www
        cd ftc_www
        .github/workflows/deploy.sh
      env:
        token: ${{ secrets.GITHUB_TOKEN }}
